
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ATT DIVC DIVO INFOSC INFOSO ITC ITO TOKC TOKO TXTC TXTO VAL WORD\n\t\ttext : TXTO lsttok TXTC\n\t\t\t\t| lsttok\n\t\t\n\t\tlsttok : tok lsttok \n\t\t\t\t| DIVO lsttok DIVC lsttok\n\t\t\t\t|\n\t\t\n\t\ttok : TOKO infos WORD TOKC\n\t\t\n\t\tinfos : INFOSO lstitems INFOSC\n\t\t\n\t\tlstitems : items lstitems\n\t\t\t\t| \n\t\t\n\t\titems : ITO lstattval ITC\n\t\t\n\t\tlstattval : attval lstattval\n\t\t\t\t| \n\t\t\n\t\tattval : ATT VAL\n\t\t'
    
_lr_action_items = {'TXTO':([0,],[2,]),'DIVO':([0,2,4,5,13,19,],[5,5,5,5,5,-6,]),'$end':([0,1,3,4,8,12,13,18,19,],[-5,0,-2,-5,-3,-1,-5,-4,-6,]),'TOKO':([0,2,4,5,13,19,],[6,6,6,6,6,-6,]),'TXTC':([2,4,7,8,13,18,19,],[-5,-5,12,-3,-5,-4,-6,]),'DIVC':([4,5,8,9,13,18,19,],[-5,-5,-3,13,-5,-4,-6,]),'INFOSO':([6,],[11,]),'WORD':([10,20,],[14,-7,]),'INFOSC':([11,15,16,21,25,],[-9,20,-9,-8,-10,]),'ITO':([11,16,25,],[17,17,-10,]),'TOKC':([14,],[19,]),'ITC':([17,22,23,26,27,],[-12,25,-12,-11,-13,]),'ATT':([17,23,27,],[24,24,-13,]),'VAL':([24,],[27,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'text':([0,],[1,]),'lsttok':([0,2,4,5,13,],[3,7,8,9,18,]),'tok':([0,2,4,5,13,],[4,4,4,4,4,]),'infos':([6,],[10,]),'lstitems':([11,16,],[15,21,]),'items':([11,16,],[16,16,]),'lstattval':([17,23,],[22,26,]),'attval':([17,23,],[23,23,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> text","S'",1,None,None,None),
  ('text -> TXTO lsttok TXTC','text',3,'p_text','Tokxml.py',166),
  ('text -> lsttok','text',1,'p_text','Tokxml.py',167),
  ('lsttok -> tok lsttok','lsttok',2,'p_lsttok','Tokxml.py',176),
  ('lsttok -> DIVO lsttok DIVC lsttok','lsttok',4,'p_lsttok','Tokxml.py',177),
  ('lsttok -> <empty>','lsttok',0,'p_lsttok','Tokxml.py',178),
  ('tok -> TOKO infos WORD TOKC','tok',4,'p_tok','Tokxml.py',190),
  ('infos -> INFOSO lstitems INFOSC','infos',3,'p_infos','Tokxml.py',199),
  ('lstitems -> items lstitems','lstitems',2,'p_lstitems','Tokxml.py',205),
  ('lstitems -> <empty>','lstitems',0,'p_lstitems','Tokxml.py',206),
  ('items -> ITO lstattval ITC','items',3,'p_items','Tokxml.py',215),
  ('lstattval -> attval lstattval','lstattval',2,'p_lstattval','Tokxml.py',221),
  ('lstattval -> <empty>','lstattval',0,'p_lstattval','Tokxml.py',222),
  ('attval -> ATT VAL','attval',2,'p_attval','Tokxml.py',234),
]
